---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.8.x
    - 1.9.x
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "cd6jTZ8KUYvRmyYclBiuypChOX9yCgt9NyOfJIQu9J1UjqnvjvLtB4dmS/yuTX3ZDMsOo075C95qVG/WjlDLDrUI5Ffbv8zzigAg2A0xvOeq4Zva1abg8A+yQaaXNrKCnzjuiQLE/QT/WvOXzwrm878KYImhfCd0aXb9JFXVLVZYZBdDAJO2mNBXv4NKGjMKD3l43f3kD0q+cw1DbDxR4/EpkWeBPLGzW/9xHnqnkJdD/LLQKvwZEEzExcvvI9wGbKtGdZElvKAVMwTXMwLBpVcwXIXWQNEQ+EBqLDRmfillI1esl2hSakle4WPhfdjeii/RGuiEleC1yjmQ3ftvLaGKNyh8bsY/Ine7gizSVm368ghedRaHfCQawsG02m8XCitnic+kfNfviygNPwid9hSYxTLwXYEr9q2fVIobikoaBe6LxFM1qjSnqvCL25unI1dS5Qf6ZuP7Zi7EPxcwonApX3yJJyALS9wdu9A2GJVNuIwucNXh+UIX0CZPaPNNW/PKiDSAg+igOLGAua7on6rSjSLtzBJIhU4mQIWIHNc3G+vLK+CtswNw80ITItWfH/ZaiiO279V5oLEBVBaUAP2d5Ut/YaDilDfrIcxRIi3lyyXieFEkjzNxKr2jrRODWPoeulbO6/EeZpd8VieDUYAWhyMxYlu99aE2oYzbkwo="
    file:
      - cross/upmail-linux-amd64.md5
      - cross/upmail-linux-amd64.sha256
      - cross/upmail-linux-amd64
    skip_cleanup: true
    on:
      go: 1.9.x
      tags: true
